name: Build & Deploy
on:
  push:
    branches:
    - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}} 
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            cd tshirtstoreapi
            rm -rf tshirtstore
            git clone git@github.com:vaibhav35/tshirtstore.git
            touch ./tshirtstore/.env
            echo "${{secrets.ENV_FILE}}" > .env
            npm ci
            echo 'Deployed successfully on digitalocean droplet '
